#Requires AutoHotkey v2.0

; Mapping Constants

A := "{Left}"
W := "{Up}"
S := "{Down}"
D := "{Right}"

; Mapping Commands

COMMAND__SUPPORT__MACHINE_GUN := [S, A, S, W, D]
COMMAND__SUPPORT__ANTI_MATERIAL_RIFLE := [S, A, D, W, S]
COMMAND__SUPPORT__STALWART := [S, A, S, W, W, A]
COMMAND__SUPPORT__RECOILLESS_RIFLE := [S, A, D, D, A]
COMMAND__SUPPORT__FRAMETHROWER := [S, A, W, S, W]
COMMAND__SUPPORT__AUTOCANNON := [S, D, A, S, S, W, W, D]
COMMAND__SUPPORT__LASERCANNON := [S, A, S, W, A]
COMMAND__SUPPORT__GRENADE_LAUNCHER := [S, A, W, A, S]
COMMAND__SUPPORT__BALLISTIC_SHIELD_BACKPACK := [S, A, S, S, W, A]
COMMAND__SUPPORT__SUPPLY_PACK := [S, A, S, W, W, S]
COMMAND__SUPPORT__RAILGUN := [S, D, S, W, A, D]
COMMAND__SUPPORT__ARC_THROWER := [S, D, S, W, A, A]
COMMAND__SUPPORT__EXPENDABLE_ANTI_TANK := [S, S, A, W, D]
COMMAND__SUPPORT__SPEAR := [S, S, W, S, S]
COMMAND__SUPPORT__SHILD_GENERATOR_PACK := [S, W, A, D, A, D]
COMMAND__SUPPORT__JUMP_PACK := [S, W, W, S, W]
COMMAND__SUPPORT__GUARD_DOG_ROVER := [S, W, A, W, D, D]
COMMAND__SUPPORT__GUARD_DOG := [S, W, A, W, D, S]

COMMAND__SENTRY__TESLA_TOWER := [S, W, D, W, A, D]
COMMAND__SENTRY__HMG_EMPLACEMENT := [S, W, A, D, D, A]
COMMAND__SENTRY__MACHINE_GUN_SENTRY := [S, W, D, D, W]
COMMAND__SENTRY__GATLING_SENTRY := [S, W, D, A]
COMMAND__SENTRY__MORTAR_SENTRY := [S, W, D, D, S]
COMMAND__SENTRY__AUTOCANNON_SENTRY := [S, W, D, W, A, W]
COMMAND__SENTRY__ROCKET_SENTRY := [S, W, D, D, A]
COMMAND__SENTRY__EMP_MORTAR_SENTRY := [S, W, D, S, D]
COMMAND__SENTRY__SHIELD_GENERATOR_RELAY := [S, S, A, D, A, D]
COMMAND__SENTRY__ANTI_PERSONNEL_MINEFIELD := [S, A, W, D]
COMMAND__SENTRY__INCENDIARY_MINES := [S, A, A, S]

COMMAND__TEAM__REINFORCE := [W, S, D, A, W]
COMMAND__TEAM__SOS_BEACON := [W, S, D, W]
COMMAND__TEAM__RESUPPLY := [S, S, W, D]

COMMAND__ORBITAL__GATLING_BARRAGE := [D, S, A, W, W]
COMMAND__ORBITAL__WALKING_BARRAGE := [D, S, D, S, D, S]
COMMAND__ORBITAL__LASER := [D, S, W, D, S]
COMMAND__ORBITAL__RAILCANNON_STRIKE := [D, W, S, S, D]
COMMAND__ORBITAL__AIRBURST_STRIKE := [D, D, D]
COMMAND__ORBITAL__120MM_HE_BARRAGE := [D, D, S, A, D, S]
COMMAND__ORBITAL__380MM_HE_BARRAGE := [D, S, W, W, A, S, S]
COMMAND__ORBITAL__PRECISION_STRIKE := [D, D, W]
COMMAND__ORBITAL__EMS_STRIKE := [D, D, A, S]
COMMAND__ORBITAL__GAS_STRIKE := [D, D, S, D]
COMMAND__ORBITAL__SMOKE_STRIKE := [D, D, S, W]

COMMAND__EAGLE__STRAFING_RUN := [W, D, D]
COMMAND__EAGLE__AIRSTRIKE := [W, D, S, D]
COMMAND__EAGLE__CLUSTER_BOMB := [W, D, S, S, D]
COMMAND__EAGLE__EAGLE_NAPALM_AIRSTRIKE := [W, D, S, W]
COMMAND__EAGLE__SMOKE_STRIKE := [W, D, W, S]
COMMAND__EAGLE__110MM_ROCKET_PODS := [W, D, W, A]
COMMAND__EAGLE__500KG_BOMB := [W, D, S, S, S]

call_command(commands) {
    for cmd in commands
    {
        Send cmd ; Send the command
        Sleep 100 ; Delay of 0.1 seconds
    }
}

; Mappping Key-Bindings
; == Example ==
;
; ^Numpad1:: call_command(COMMAND__SUPPORT__RAILGUN) ; Ctrl + Numpad1
; ^1:: call_command(COMMAND__SUPPORT__RAILGUN) ; Ctrl + 1
; ^+1:: call_command(COMMAND__SUPPORT__RAILGUN) ; Ctrl + Shift + 1
; ^!1:: call_command(COMMAND__SUPPORT__RAILGUN) ; Ctrl + Alt + 1


^1:: call_command(COMMAND__SUPPORT__RAILGUN)
^2:: call_command(COMMAND__SUPPORT__SUPPLY_PACK)
^3:: call_command(COMMAND__SUPPORT__GUARD_DOG_ROVER)
^4:: call_command(COMMAND__SUPPORT__GRENADE_LAUNCHER)

^5:: call_command(COMMAND__ORBITAL__RAILCANNON_STRIKE)
^6:: call_command(COMMAND__ORBITAL__PRECISION_STRIKE)

^+1:: call_command(COMMAND__TEAM__REINFORCE)
^+2:: call_command(COMMAND__TEAM__RESUPPLY)

^!1:: call_command(COMMAND__SENTRY__GATLING_SENTRY)
^!2:: call_command(COMMAND__SENTRY__SHIELD_GENERATOR_RELAY)

MsgBox "Activated - Helldivers Stratagems Mapping"